/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SIPProjection = IDL.Record({
  'totalInvested' : IDL.Nat,
  'wealthGain' : IDL.Nat,
  'projectedReturnRate' : IDL.Nat,
  'projectedCorpus' : IDL.Nat,
});
export const FundRecommendation = IDL.Record({
  'cagr' : IDL.Nat,
  'sharpeRatio' : IDL.Nat,
  'fundName' : IDL.Text,
  'category' : IDL.Text,
  'riskLevel' : IDL.Text,
  'riskScore' : IDL.Nat,
});
export const RiskProfile = IDL.Record({
  'profileType' : IDL.Text,
  'riskScore' : IDL.Nat,
});
export const SIPSubmission = IDL.Record({
  'goalAmount' : IDL.Nat,
  'yearlyInvestmentAmount' : IDL.Nat,
  'monthlyAmount' : IDL.Nat,
  'existingCorpus' : IDL.Nat,
  'tenureYears' : IDL.Nat,
  'investorName' : IDL.Text,
});
export const SIPSession = IDL.Record({
  'id' : IDL.Nat,
  'recommendations' : IDL.Vec(FundRecommendation),
  'riskProfile' : RiskProfile,
  'projection' : SIPProjection,
  'submission' : SIPSubmission,
});

export const idlService = IDL.Service({
  'calculateSIPProjection' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [SIPProjection],
      [],
    ),
  'getFundRecommendations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FundRecommendation)],
      [],
    ),
  'getRegisteredEmailCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getReportDataByName' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'recommendations' : IDL.Vec(FundRecommendation),
          'riskProfile' : IDL.Opt(RiskProfile),
          'projection' : IDL.Opt(SIPProjection),
          'submission' : IDL.Opt(SIPSubmission),
        }),
      ],
      [],
    ),
  'getReportsGenerated' : IDL.Func([], [IDL.Nat], ['query']),
  'getSIPReport' : IDL.Func([IDL.Nat, IDL.Text], [SIPSession], []),
  'getSipReportsBySessionIds' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(SIPSession)],
      [],
    ),
  'submitRiskProfile' : IDL.Func([IDL.Text, IDL.Nat], [RiskProfile], []),
  'submitSIPDetails' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SIPProjection = IDL.Record({
    'totalInvested' : IDL.Nat,
    'wealthGain' : IDL.Nat,
    'projectedReturnRate' : IDL.Nat,
    'projectedCorpus' : IDL.Nat,
  });
  const FundRecommendation = IDL.Record({
    'cagr' : IDL.Nat,
    'sharpeRatio' : IDL.Nat,
    'fundName' : IDL.Text,
    'category' : IDL.Text,
    'riskLevel' : IDL.Text,
    'riskScore' : IDL.Nat,
  });
  const RiskProfile = IDL.Record({
    'profileType' : IDL.Text,
    'riskScore' : IDL.Nat,
  });
  const SIPSubmission = IDL.Record({
    'goalAmount' : IDL.Nat,
    'yearlyInvestmentAmount' : IDL.Nat,
    'monthlyAmount' : IDL.Nat,
    'existingCorpus' : IDL.Nat,
    'tenureYears' : IDL.Nat,
    'investorName' : IDL.Text,
  });
  const SIPSession = IDL.Record({
    'id' : IDL.Nat,
    'recommendations' : IDL.Vec(FundRecommendation),
    'riskProfile' : RiskProfile,
    'projection' : SIPProjection,
    'submission' : SIPSubmission,
  });
  
  return IDL.Service({
    'calculateSIPProjection' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [SIPProjection],
        [],
      ),
    'getFundRecommendations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FundRecommendation)],
        [],
      ),
    'getRegisteredEmailCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getReportDataByName' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'recommendations' : IDL.Vec(FundRecommendation),
            'riskProfile' : IDL.Opt(RiskProfile),
            'projection' : IDL.Opt(SIPProjection),
            'submission' : IDL.Opt(SIPSubmission),
          }),
        ],
        [],
      ),
    'getReportsGenerated' : IDL.Func([], [IDL.Nat], ['query']),
    'getSIPReport' : IDL.Func([IDL.Nat, IDL.Text], [SIPSession], []),
    'getSipReportsBySessionIds' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(SIPSession)],
        [],
      ),
    'submitRiskProfile' : IDL.Func([IDL.Text, IDL.Nat], [RiskProfile], []),
    'submitSIPDetails' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };