/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FundRecommendation {
  'cagr' : bigint,
  'sharpeRatio' : bigint,
  'fundName' : string,
  'category' : string,
  'riskLevel' : string,
  'riskScore' : bigint,
}
export interface RiskProfile { 'profileType' : string, 'riskScore' : bigint }
export interface SIPProjection {
  'totalInvested' : bigint,
  'wealthGain' : bigint,
  'projectedReturnRate' : bigint,
  'projectedCorpus' : bigint,
}
export interface SIPSession {
  'id' : bigint,
  'recommendations' : Array<FundRecommendation>,
  'riskProfile' : RiskProfile,
  'projection' : SIPProjection,
  'submission' : SIPSubmission,
}
export interface SIPSubmission {
  'goalAmount' : bigint,
  'yearlyInvestmentAmount' : bigint,
  'monthlyAmount' : bigint,
  'existingCorpus' : bigint,
  'tenureYears' : bigint,
  'investorName' : string,
}
export interface _SERVICE {
  'calculateSIPProjection' : ActorMethod<
    [string, bigint, bigint, bigint],
    SIPProjection
  >,
  'getFundRecommendations' : ActorMethod<[string], Array<FundRecommendation>>,
  'getRegisteredEmailCount' : ActorMethod<[], bigint>,
  'getReportDataByName' : ActorMethod<
    [string],
    {
      'recommendations' : Array<FundRecommendation>,
      'riskProfile' : [] | [RiskProfile],
      'projection' : [] | [SIPProjection],
      'submission' : [] | [SIPSubmission],
    }
  >,
  'getReportsGenerated' : ActorMethod<[], bigint>,
  'getSIPReport' : ActorMethod<[bigint, string], SIPSession>,
  'getSipReportsBySessionIds' : ActorMethod<
    [string, bigint, bigint],
    Array<SIPSession>
  >,
  'submitRiskProfile' : ActorMethod<[string, bigint], RiskProfile>,
  'submitSIPDetails' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, bigint],
    [bigint, string, bigint, bigint, bigint, bigint, bigint]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];